Method : osnet_ain_x0_75_geo
Dataset : University
PROJECT_NAME : 03160926-osnet_ain_x0_75_geo-wh1_Re
epochs : 131
views : 2
block : 4
lr : 0.001
droprate : 0.75
pretrained : True
fp16 : False
transforms : default
criterion : CrossEntropy
loss : triplet
h_w : 1
pool : avg
data_dir : /storage4/wangzhen/University-Release/train
test_data_dir : /storage4/wangzhen/University-Release/test
batchsize : 8
stride : 1
pad : 10
h : 256
w : 256
erasing_p : 0
use_dense : False
warm_epoch : 0
resume : False
share : True
extra_Google : True 